### ISSUE TITLE
frame rates

### ISSUE THREAD

**Issue by GOBish** [NobuoTsukamoto/edge_tpu#1]
Hi,
What frame rates are you experiencing with deeplabV3 using a webcam on a coral edge tpu?

**Comment by NobuoTsukamoto** [comment]
With PiCamera + Raspberry Pi 4 + Edge TPU, it is about 5.5 FPS.

The following sample.
- https://github.com/NobuoTsukamoto/edge_tpu/tree/master/deeplab/cpp/transparent
- Youtube link: https://www.youtube.com/watch?v=gZxDs8-sA8c

For your reference.
I posted a benchmark on Raspberry Pi 3 + Edge TPU on my blog.(It's in Japanese)
https://nextremer-nbo.blogspot.com/2019/10/edge-tpudeeplabv3september-2019-updates.html

**Comment by NobuoTsukamoto** [comment]
Close the issue. If you have any problems, please open it again.
