### ISSUE TITLE
Class limit on semantic segmentation

### ISSUE THREAD

**Issue by Hi-Zed** [NobuoTsukamoto/edge_tpu#2]
Hi,
amazing repo, I got my hands on an Edge TPU but I am struggling in finding an actually useful way to use it.
I am interested in doing only instance segmentation (so no classification whatsoever), and I was wondering if in your semantic segmentation approach based on DeepLabV3 you are limited to the same 20 classes listed [here](https://coral.ai/models/).

Thanks

**Comment by NobuoTsukamoto** [comment]
> I am interested in doing only instance segmentation (so no classification whatsoever), 

I also want to perform instance segmentation (like Mask R-CNN) on an Edge TPU. However, I don't know the model that can be executed. I would like to know if you can.

> I was wondering if in your semantic segmentation approach based on DeepLabV3 you are limited to the same 20 classes listed here.

Yes. As you pointed out. The model for this repository and Coral's Deep Lab is PASCAL VOC. If you want to model your original dataset, [this link](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/quantize.md) will help.

Thanks

**Comment by Hi-Zed** [comment]
I found a couple of resources to convert Mask R-CNN to TFLite, unfortunately, nothing specifically targeted to the Edge TPU.
[This article](https://wathek.medium.com/convert-mask-r-cnn-model-to-tflite-with-tensorflow-2-3-57160d3be18d), and associated [colab notebook](https://drive.google.com/file/d/1TUb5GOzrYlCew4JFqOC-utBMm0Pkm71e/view), give some instruction on how to create the model to TFLite. I downloaded it, but I was unsuccessful in running it on the Edge TPU.

Another option is [this repo](https://github.com/gustavz/Mobile_Mask_RCNN) creates a version of Mask RCNN using MobileNet. I am very new to TensorFlow and deep learning in general, so I am not sure how to run this version on the Edge TPU, but maybe you can find it useful.

**Comment by NobuoTsukamoto** [comment]
@Hi-Zed 
See this.
https://github.com/PINTO0309/PINTO_model_zoo/tree/master/074_Yolact
YOLACT (Real-time Instance Segmentation) edge tpu model.

**Comment by NobuoTsukamoto** [comment]
Close the issue. If you have any problems, please open it again.
