### ISSUE TITLE
The link to the video appears to be broken.

### ISSUE THREAD

**Issue by PINTO0309** [NobuoTsukamoto/edge_tpu#5]
Here. :smiley: 
https://github.com/NobuoTsukamoto/tflite-cv-example/tree/master/deeplab_edgetpu2#coral-dev-board-edgetpu-autosegedgetpu-xs-with-fusing-argmax
![Screenshot 2021-12-03 21:37:18](https://user-images.githubusercontent.com/33194443/144603829-77d81fff-f9ef-4a9f-98ea-99376bde160f.png)

**Comment by NobuoTsukamoto** [comment]
Thanks!
Fixed. b40311960b9755eb59c7c03860fec801dccc2210

**Comment by NobuoTsukamoto** [comment]
I also fixed the PINTO_model_zoo demo page.
https://github.com/PINTO0309/PINTO_model_zoo/commit/8f23df5dcd5f81057976fb6f527142678cec69ea
